name: Mi primer workflow

on: [push]

jobs:
  ejemplo:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v4

      - name: Mostrar mensaje
        run: echo "Hola GitHub Actions"
